export class User {

    constructor(
        public apiUrl?: string,
        public apiUrldesc?: string,
        public cidade ?: string,
        public humidade ?: string ,
        public temperatura ?: number,
        public minima ?: number,
        public maxima ?:  number,
        public descricao ?: string,
        public uf?: string,
        public descicon?: string,
        public uficon?: string,
        public cidadeid?: number,
        public cidadedia?: string,
        public ufdesc?: string,
        public tempo?: string,
        public max1 ?: number,
        public min1?: number,
        public desc1?: string,
        public icon1?: string,
        public max2 ?: number,
        public min2?: number,
        public desc2?: string,
        public icon2?: string,
        public max3 ?: number,
        public min3?: number,
        public desc3?: string,
        public icon3?: string,
        public max4 ?: number,
        public min4?: number,
        public desc4?: string,
        public icon4?: string,
        public max5 ?: number,
        public min5?: number,
        public desc5?: string,
        public icon5?: string,       
        ) { }
}